### ISSUE TITLE
Pull custom image for devo header

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/newspring-app#131]

**Comment by johnthepink** [comment]
No more leather?

John Pinkerton

On Tue, Feb 23, 2016 at 11:41 AM James Baxley

<
mailto:James Baxley <notifications@github.com>
> wrote:

—

Reply to this email directly or
https://github.com/NewSpring/newspring-app/issues/131
.

https://github.com/NewSpring/newspring-app/issues/131

**Comment by jbaxleyiii** [comment]
@johnthepink devos in EE can set a custom image. The priority should be custom image -> in content image -> leather
