### ISSUE TITLE
Liked content breeding like rabbits

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/newspring-app#150]
## Steps to Reproduce:
1. Like a piece of content.
2. Go to Profile, select an item of content you have liked.
3. Unlike the piece of content.
4. Go back to profile, the piece of content will now be in there twice, you can keep doing this to add the content many times over.

**Comment by jbaxleyiii** [comment]
this bug is back?!

**Comment by jbaxleyiii** [comment]
@samclaridge I haven't been able to replicate :-1:

**Comment by samclaridge** [comment]
Samuel Claridge

— Sent from
https://polymail.io/

On Tue, Feb 23, 2016 at 9:36 PM James Baxley

<
mailto:James Baxley <notifications@github.com>
> wrote:

https://github.com/samclaridge
I haven't been able to replicate

**Comment by jbaxleyiii** [comment]
okay I added a check that *should* fix this
