### ISSUE TITLE
Android: Sign Out button not styled

### ISSUE THREAD

**Issue by dcs619** [NewSpring/newspring-app#162]
![image](https://cloud.githubusercontent.com/assets/1210933/13291884/904d6a2c-dae7-11e5-88b8-1f33a3f1a541.png)

**Comment by johnthepink** [comment]
This is fixed, and will be present in next Android build 

![screenshot 2016-03-16 16 42 28](https://cloud.githubusercontent.com/assets/816517/13828089/2488d564-eb96-11e5-8512-0d1b9f6e80da.png)

**Comment by dcs619** [comment]
![dior-daphe-groeneveld-4MIj40tduL0Ji](https://camo.githubusercontent.com/aeaabf24c8a9c050591858bd49abf0ecdc211f71/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f344d496a34307464754c304a692f67697068792e676966)
