### ISSUE TITLE
Android: links in articles don't open the in-app browser 

### ISSUE THREAD

**Issue by dcs619** [NewSpring/newspring-app#163]
I'm not entirely sure the problem isn't my phone.  I have the stock browser (Chrome) disabled.

When clicking links in articles, nothing happens.  Occasionally if I click it 3+ times, I get a spinning green wheel on a black background.

![image](https://cloud.githubusercontent.com/assets/1210933/13291955/d1a58d42-dae7-11e5-8c3e-af70f9049ccc.png)

**Comment by johnthepink** [comment]
All of the links in this article open externally in iOS, but I'll leave open for Android testing when I get there
