### ISSUE TITLE
Android: NewSpring Logo went to CrossFit

### ISSUE THREAD

**Issue by dcs619** [NewSpring/newspring-app#165]
On startup

![image](https://cloud.githubusercontent.com/assets/1210933/13292105/7fa2b5be-dae8-11e5-9617-d6f292046bb4.png)

**Comment by johnthepink** [comment]
Based off research @samclaridge did, I'm not totally sure Meteor currently suppports this. There are only a couple sizes they accept. 

We are on 1.3-beta.11, so possibly they have fixed this. We may have to do a custom build, or fork to fix.

**Comment by johnthepink** [comment]
As of 1.3-rc.2, there aren't any different android screen sizes. Will have to update to see if the build has changed any. 

https://github.com/meteor/meteor/blob/a9c32ed699f3aba89c43f011023b7f431921ca44/tools/cordova/builder.js#L49-L58

**Comment by dcs619** [comment]
Which resolution does the app use now?  My phone resolution is 1440 x 2560

**Comment by johnthepink** [comment]
@dcs619 i would imagine you are seeing the `1440x1080`

https://github.com/NewSpring/newspring-app/blob/master/mobile-config.js#L55
