### ISSUE TITLE
Process after launch

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/newspring-app#170]
After launch, we are going to need a better process in place for changes to EE items. For instances, when devotions switch how they are using images, or stories switch how they are publishing, etc. 

We should probably have:

- information when items are being changed in EE 

- beta version of app that checks against beta server as sign off for changed

- ability to check future items in app for changes missed 

Etc. 

It would be a shame for stuff to show up in app and we have to respond to it. Instead let's figure out how to be proactive.

**Comment by richarddubay** [comment]
@johnthepink That's on me. I've been very lack in letting you guys know what we were working on and, honestly, I've forgotten more times then not to even include the app as part of the conversation. Here's to better days!

**Comment by johnthepink** [comment]
@richarddubay no worries! I know you guys have too much on your plate, and you're killing it. Just wanted to document this somewhere so we can remember to get it all straightened out. You're the best <3
