### ISSUE TITLE
QA: Video playback on Android

### ISSUE THREAD

**Issue by dcs619** [NewSpring/newspring-app#187]
I'm opening this issue for QA since @briankalwat and I realized the current Subsplash app provides the only Android solution for video streaming (and also provides Chromecast support).

Currently Ooyala forces Android users to download a separate app when using the browser in Android. They have not been receptive to change 😒

A possible workaround is to request desktop view in Android for mobile video. This bypasses Ooyala's byzantine requirement to download HOOK, but may not be future-proof.

**Comment by johnthepink** [comment]
@dcs619 @briankalwat closing because we are moving issues to our monolithic project https://github.com/NewSpring/Apollos/issues/627
