### ISSUE TITLE
integrate webview

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/newspring-app#2]

**Comment by johnthepink** [comment]
@jbaxleyiii it appears there has been some trouble with WKWebView and meteor 1.2 https://github.com/practicalmeteor/meteor-wkwebview/issues/8

I'm investigating

**Comment by jbaxleyiii** [comment]
@johnthepink :( sad panda

**Comment by johnthepink** [comment]
doesn't seem to work with 1.1.0.3 either

**Comment by johnthepink** [comment]
holding off until wkwebview issues get sorted

**Comment by johnthepink** [comment]
Official Meteor support coming https://forums.meteor.com/t/meteor-1-2-ios-wkwebview/11055

**Comment by johnthepink** [comment]
@jbaxleyiii got this working with https://atmospherejs.com/silvervue/wkwebview which was posted on friday
