### ISSUE TITLE
Helpers Refactor

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/newspring-app#34]
ContentHelpers needs to be refactored so the functions take the actual item it is helping. Not account for a series of possible items being passed in. That was a bad idea.

**Comment by jbaxleyiii** [comment]
![](https://media0.giphy.com/media/P2ND2IWEBv4pa/200.gif)

**Comment by johnthepink** [comment]
![](http://i.giphy.com/ewFAM2ATdw9Ne.gif)
