### ISSUE TITLE
Music Player Remix

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/newspring-app#63]
This is funny. 

If you start the music player, then navigate to profile, the mini player dies. But, the song keeps playing. 

Then, if you navigate back to albums and click a new song, you can start another song. Then the two songs play at the same time. 

I assume you can do this over and over and have a sweet remix. I also assume it has something to do with the code splitting.

**Comment by jbaxleyiii** [comment]
@johnthepink I bet it is because the profile isn't using the app layout. It is using global

**Comment by johnthepink** [comment]
Ah hah!
